### PR TITLE
Created Mobile Responsive Version of b/beverages

### PR DESCRIPTION
**Pull request by zent-lim**

### CODE REVIEW

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

(1) OK!

(2) OK! In that case, I wouldn't require you to add the comments with your name and the date near the portions you modify.
--> Having said this, I hope you'll let me continue adding such comments whenever I deem necessary.
--> The comments actually do help me do the following:

a) Remember if I've already done a particular code solution, because there would be times when I'd also comment out my earlier solution.

b) Remember when I last updated a particular portion of the code.

c) Remember what I added in the core code.

May I kindly ask if you would agree to include your name and the date, along with the comments you add to explain certain portions of the code?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike,

On Fri, May 4, 2018, 8:46 AM Masarap Mabuhay, <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the reply.
>
> (1) OK!
>
> (2) OK! In that case, I wouldn't require you to add the comments with your
> name and the date near the portions you modify.
> --> Having said this, I hope you'll let me continue adding such comments
> whenever I deem necessary.
> --> The comments actually do help me do the following:
>
> a) Remember if I've already done a particular code solution, because there
> would be times when I'd also comment out my earlier solution.
>
> b) Remember when I last updated a particular portion of the code.
>
> c) Remember what I added in the core code.
>
Ok!

> May I kindly ask if you would agree to include your name and the date,
> along with the comments you add to explain certain portions of the code?
>
Ok!

For code that's not so easy to follow, i usually have comments placed
already.

Do you have a particular patch of code in mind?

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! Yes, I've seen your comments to explain portions of the code you added.

At present, no, I do not have a particular patch of code in mind.

However, from experience reading and updating your code, I am able to understand what you write.

If there's anything unclear, I would send you a question or open an issue here on GitHub.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Okly dokly. Morning!

**Comment by masarapmabuhay** [comment]
OK! Thank you!

Peace,
Mike

**Pull request merged**
