### PR TITLE
Added Kick Button to Auto Email Home Page.

### PR DESCRIPTION
**Pull request by zent-lim**
HI Mike,

This is an early sample so we can check if the kick button is compatible with your live server.

Note:

(1) Email Preview Button is not yet Functional.

### CODE REVIEW

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the message.

OK. Let me check it then.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
As it turned out, I was able
to update my local GitHub repo,
but not dev and prod.

After updating them accordingly,
the "Send Email" button worked.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike!

Awesome!

This closes the biggest risk of phase 2. The remaining tasks are only a
matter of time.

Catch up with you on sat weekly update. 😀

**Comment by masarapmabuhay** [comment]
OK, Zent! Thank you!

Peace,
Mike

**Pull request merged**
