### PR TITLE
Added breadcrumbs to auto-email feature.

### PR DESCRIPTION
**Pull request by zent-lim**
Hi Mike,

I added breadcrumbs to auto-email admin module as action item to the feed back below:

Mike: Is there a way to go back to the auto-email home page from the other pages?

Zent: Currently, there is none. I'll add this functionality as feedback for phase 1. I'll push code by end of week.

Have a good day ahead.

### CODE REVIEW

**Comment by masarapmabuhay** [comment]
Hi Zent,
OK! Thank you!

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
I've merged this latest commit of yours.
I've also looked into the updated interface, but was unable to verify what changed in the front-end.

Should there really be any noticeable changes?
If so, can you tell me what I am unable to see?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike!

Please see attached file where the new element is marked in circle.

All auto email pages now have bread crumbs so you can easily navigate back
to a previous hierarchy.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Can you resend the attached file you mentioned in your message?
It seems that it wasn't included.

Thank you.

Have a pleasant morning.

Peace,
Mike
p.s. may I ask if you came up with the term "bread crumbs", which seems like a set of CSS configurations designed specifically for auto-email?

**Comment by zent-lim** [comment]
Morning Mike!

I ll send the attachment to ur personal email when i get access to laptop
round 2 pm.

P.s.
Breadcrumbs is an old term. Not sure who coined it. I think it came from
the old children story where they leave a trail of breadcrumbs to find
their way back home from a forest. It serves the same purpose for our use
case.

On Nov 22, 2017 9:42 AM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
Thank you for the reply.

Can you resend the attached file you mentioned in your message?
It seems that it wasn't included.

Thank you.

Have a pleasant morning.

Peace,
Mike
p.s. may I ask if you came up with the term "bread crumbs", which seems
like a set of CSS configurations designed specifically for auto-email?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/pull/26#issuecomment-346217179>, or mute
the thread

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! Yes, I received your email with the screenshot, which you got from your mobile gmail.

Peace,
Mike
p.s. OK. From what I can understand, what you mean is that "bread crumbs" in this case acts as a way to navigate in the hierarchy of auto-email.

**Comment by zent-lim** [comment]
Hi Mike,

Yep. Have a good day ahead! ☺

**Comment by masarapmabuhay** [comment]
OK! Thank you, Zent!

Peace,
Mike

**Pull request merged**
